<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SinkronisasisTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sinkronisasis')->delete();
        
        \DB::table('sinkronisasis')->insert(array (
            0 => 
            array (
                'id' => 1,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Komunikasi Dan Penyiaran Islam',
                'pelayanan_online' => 13,
                'pelayanan_offline' => 4,
                'pendaftar' => 34,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 3,
                'nim' => 6,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            1 => 
            array (
                'id' => 2,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
            'prodi' => 'Pendidikan Agama Islam (S1)',
                'pelayanan_online' => 40,
                'pelayanan_offline' => 14,
                'pendaftar' => 125,
                'bayar_form_reguler' => 11,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 3,
                'bayar_form_kipk' => 22,
                'nim' => 37,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            2 => 
            array (
                'id' => 3,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Pendidikan Guru Madrasah Ibtidaiyah',
                'pelayanan_online' => 16,
                'pelayanan_offline' => 2,
                'pendaftar' => 95,
                'bayar_form_reguler' => 16,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 20,
                'nim' => 38,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            3 => 
            array (
                'id' => 4,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Perbankan Syari`ah',
                'pelayanan_online' => 3,
                'pelayanan_offline' => 4,
                'pendaftar' => 50,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 5,
                'nim' => 9,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            4 => 
            array (
                'id' => 5,
                'fakultas' => 'FAKULTAS EKONOMI',
                'prodi' => 'Akuntansi',
                'pelayanan_online' => 18,
                'pelayanan_offline' => 5,
                'pendaftar' => 103,
                'bayar_form_reguler' => 5,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 2,
                'bayar_form_kipk' => 31,
                'nim' => 39,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            5 => 
            array (
                'id' => 6,
                'fakultas' => 'FAKULTAS EKONOMI',
                'prodi' => 'Manajemen',
                'pelayanan_online' => 58,
                'pelayanan_offline' => 28,
                'pendaftar' => 197,
                'bayar_form_reguler' => 10,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 2,
                'bayar_form_kipk' => 47,
                'nim' => 59,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            6 => 
            array (
                'id' => 7,
                'fakultas' => 'FAKULTAS HUKUM',
            'prodi' => 'Ilmu Hukum (S1)',
                'pelayanan_online' => 48,
                'pelayanan_offline' => 18,
                'pendaftar' => 122,
                'bayar_form_reguler' => 13,
                'bayar_form_rpl' => 4,
                'bayar_form_karyawan' => 6,
                'bayar_form_kipk' => 18,
                'nim' => 41,
                'bayar_ukt_reguler' => 4,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            7 => 
            array (
                'id' => 8,
                'fakultas' => 'FAKULTAS ILMU KOMUNIKASI',
                'prodi' => 'Ilmu Komunikasi',
                'pelayanan_online' => 26,
                'pelayanan_offline' => 11,
                'pendaftar' => 152,
                'bayar_form_reguler' => 8,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 43,
                'nim' => 51,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            8 => 
            array (
                'id' => 9,
                'fakultas' => 'FAKULTAS ILMU KOMUNIKASI',
                'prodi' => 'Ilmu Perpustakaan',
                'pelayanan_online' => 9,
                'pelayanan_offline' => 1,
                'pendaftar' => 14,
                'bayar_form_reguler' => 2,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 1,
                'nim' => 3,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            9 => 
            array (
                'id' => 10,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Arab',
                'pelayanan_online' => 17,
                'pelayanan_offline' => 5,
                'pendaftar' => 37,
                'bayar_form_reguler' => 9,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 3,
                'nim' => 12,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            10 => 
            array (
                'id' => 11,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Dan Sastra Indonesia',
                'pelayanan_online' => 12,
                'pelayanan_offline' => 15,
                'pendaftar' => 74,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 16,
                'nim' => 19,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            11 => 
            array (
                'id' => 12,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Inggris',
                'pelayanan_online' => 13,
                'pelayanan_offline' => 6,
                'pendaftar' => 53,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 10,
                'nim' => 14,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            12 => 
            array (
                'id' => 13,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Guru Pendidikan Anak Usia Dini',
                'pelayanan_online' => 10,
                'pelayanan_offline' => 5,
                'pendaftar' => 34,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 7,
                'nim' => 8,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            13 => 
            array (
                'id' => 14,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Luar Biasa',
                'pelayanan_online' => 43,
                'pelayanan_offline' => 15,
                'pendaftar' => 75,
                'bayar_form_reguler' => 26,
                'bayar_form_rpl' => 4,
                'bayar_form_karyawan' => 7,
                'bayar_form_kipk' => 7,
                'nim' => 44,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            14 => 
            array (
                'id' => 15,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Masyarakat',
                'pelayanan_online' => 3,
                'pelayanan_offline' => 0,
                'pendaftar' => 25,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 2,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 7,
                'nim' => 9,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            15 => 
            array (
                'id' => 16,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Matematika',
                'pelayanan_online' => 7,
                'pelayanan_offline' => 7,
                'pendaftar' => 38,
                'bayar_form_reguler' => 2,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 20,
                'nim' => 23,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            16 => 
            array (
                'id' => 17,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Pancasila dan Kewarganegaraan',
                'pelayanan_online' => 2,
                'pelayanan_offline' => 6,
                'pendaftar' => 36,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 8,
                'nim' => 10,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            17 => 
            array (
                'id' => 18,
                'fakultas' => 'FAKULTAS PERTANIAN',
                'prodi' => 'Agroteknologi',
                'pelayanan_online' => 16,
                'pelayanan_offline' => 4,
                'pendaftar' => 56,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 16,
                'nim' => 22,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            18 => 
            array (
                'id' => 19,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Administrasi Pendidikan',
                'pelayanan_online' => 38,
                'pelayanan_offline' => 9,
                'pendaftar' => 58,
                'bayar_form_reguler' => 7,
                'bayar_form_rpl' => 12,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 19,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 1,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            19 => 
            array (
                'id' => 20,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Ilmu Hukum',
                'pelayanan_online' => 18,
                'pelayanan_offline' => 14,
                'pendaftar' => 24,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 6,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 10,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            20 => 
            array (
                'id' => 21,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Pendidikan Agama Islam',
                'pelayanan_online' => 13,
                'pelayanan_offline' => 4,
                'pendaftar' => 17,
                'bayar_form_reguler' => 5,
                'bayar_form_rpl' => 3,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 8,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            21 => 
            array (
                'id' => 22,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S3 - Ilmu Pendidikan',
                'pelayanan_online' => 16,
                'pelayanan_offline' => 10,
                'pendaftar' => 13,
                'bayar_form_reguler' => 7,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 7,
                'bayar_ukt_reguler' => 2,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            22 => 
            array (
                'id' => 23,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S3 - Pendidikan Agama Islam',
                'pelayanan_online' => 3,
                'pelayanan_offline' => 4,
                'pendaftar' => 14,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 3,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            23 => 
            array (
                'id' => 24,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Elektro',
                'pelayanan_online' => 16,
                'pelayanan_offline' => 7,
                'pendaftar' => 32,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 2,
                'bayar_form_kipk' => 8,
                'nim' => 15,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            24 => 
            array (
                'id' => 25,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Industri',
                'pelayanan_online' => 11,
                'pelayanan_offline' => 5,
                'pendaftar' => 70,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 18,
                'nim' => 22,
                'bayar_ukt_reguler' => 2,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
            25 => 
            array (
                'id' => 26,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Informatika',
                'pelayanan_online' => 23,
                'pelayanan_offline' => 8,
                'pendaftar' => 90,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 36,
                'nim' => 41,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-11 22:33:43',
                'updated_at' => '2025-06-11 22:33:43',
            ),
        ));
        
        
    }
}