<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SinkronisasisTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sinkronisasis')->delete();
        
        \DB::table('sinkronisasis')->insert(array (
            0 => 
            array (
                'id' => 1,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Komunikasi Dan Penyiaran Islam',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 0,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            1 => 
            array (
                'id' => 2,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
            'prodi' => 'Pendidikan Agama Islam (S1)',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 2,
                'pendaftar' => 8,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 4,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 4,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 1,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            2 => 
            array (
                'id' => 3,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Pendidikan Guru Madrasah Ibtidaiyah',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 6,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 2,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 3,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            3 => 
            array (
                'id' => 4,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Perbankan Syari`ah',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 0,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            4 => 
            array (
                'id' => 5,
                'fakultas' => 'FAKULTAS EKONOMI',
                'prodi' => 'Akuntansi',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 1,
                'pendaftar' => 5,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 4,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            5 => 
            array (
                'id' => 6,
                'fakultas' => 'FAKULTAS EKONOMI',
                'prodi' => 'Manajemen',
                'pelayanan_online' => 5,
                'pelayanan_offline' => 6,
                'pendaftar' => 181,
                'bayar_form_reguler' => 11,
                'bayar_form_rpl' => 5,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 169,
                'nim' => 185,
                'bayar_ukt_reguler' => 180,
                'bayar_ukt_rpl' => 4,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            6 => 
            array (
                'id' => 7,
                'fakultas' => 'FAKULTAS HUKUM',
            'prodi' => 'Ilmu Hukum (S1)',
                'pelayanan_online' => 9,
                'pelayanan_offline' => 7,
                'pendaftar' => 23,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 16,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 17,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 7,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            7 => 
            array (
                'id' => 8,
                'fakultas' => 'FAKULTAS ILMU KOMUNIKASI',
                'prodi' => 'Ilmu Komunikasi',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 2,
                'bayar_form_reguler' => 2,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 2,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            8 => 
            array (
                'id' => 9,
                'fakultas' => 'FAKULTAS ILMU KOMUNIKASI',
                'prodi' => 'Ilmu Perpustakaan',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 1,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            9 => 
            array (
                'id' => 10,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Arab',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 8,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 7,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 8,
                'bayar_ukt_reguler' => 2,
                'bayar_ukt_rpl' => 4,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            10 => 
            array (
                'id' => 11,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Dan Sastra Indonesia',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 1,
                'pendaftar' => 2,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            11 => 
            array (
                'id' => 12,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Inggris',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 1,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            12 => 
            array (
                'id' => 13,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Guru Pendidikan Anak Usia Dini',
                'pelayanan_online' => 1,
                'pelayanan_offline' => 2,
                'pendaftar' => 4,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 4,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 4,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 1,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            13 => 
            array (
                'id' => 14,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Luar Biasa',
                'pelayanan_online' => 5,
                'pelayanan_offline' => 1,
                'pendaftar' => 23,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 22,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 22,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 18,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            14 => 
            array (
                'id' => 15,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Masyarakat',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 1,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 1,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            15 => 
            array (
                'id' => 16,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Matematika',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 0,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            16 => 
            array (
                'id' => 17,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Pancasila dan Kewarganegaraan',
                'pelayanan_online' => 1,
                'pelayanan_offline' => 1,
                'pendaftar' => 0,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            17 => 
            array (
                'id' => 18,
                'fakultas' => 'FAKULTAS PERTANIAN',
                'prodi' => 'Agroteknologi',
                'pelayanan_online' => 1,
                'pelayanan_offline' => 0,
                'pendaftar' => 4,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 2,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 3,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 2,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            18 => 
            array (
                'id' => 19,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Administrasi Pendidikan',
                'pelayanan_online' => 13,
                'pelayanan_offline' => 5,
                'pendaftar' => 174,
                'bayar_form_reguler' => 37,
                'bayar_form_rpl' => 117,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 154,
                'bayar_ukt_reguler' => 12,
                'bayar_ukt_rpl' => 109,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            19 => 
            array (
                'id' => 20,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Ilmu Hukum',
                'pelayanan_online' => 6,
                'pelayanan_offline' => 2,
                'pendaftar' => 86,
                'bayar_form_reguler' => 71,
                'bayar_form_rpl' => 8,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 79,
                'bayar_ukt_reguler' => 50,
                'bayar_ukt_rpl' => 3,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            20 => 
            array (
                'id' => 21,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Pendidikan Agama Islam',
                'pelayanan_online' => 4,
                'pelayanan_offline' => 1,
                'pendaftar' => 23,
                'bayar_form_reguler' => 13,
                'bayar_form_rpl' => 10,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 23,
                'bayar_ukt_reguler' => 11,
                'bayar_ukt_rpl' => 9,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            21 => 
            array (
                'id' => 22,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S3 - Ilmu Pendidikan',
                'pelayanan_online' => 5,
                'pelayanan_offline' => 1,
                'pendaftar' => 27,
                'bayar_form_reguler' => 31,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 31,
                'bayar_ukt_reguler' => 25,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            22 => 
            array (
                'id' => 23,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S3 - Pendidikan Agama Islam',
                'pelayanan_online' => 3,
                'pelayanan_offline' => 0,
                'pendaftar' => 26,
                'bayar_form_reguler' => 9,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 9,
                'bayar_ukt_reguler' => 7,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            23 => 
            array (
                'id' => 24,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Elektro',
                'pelayanan_online' => 1,
                'pelayanan_offline' => 1,
                'pendaftar' => 2,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            24 => 
            array (
                'id' => 25,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Industri',
                'pelayanan_online' => 0,
                'pelayanan_offline' => 0,
                'pendaftar' => 2,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 0,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            25 => 
            array (
                'id' => 26,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Informatika',
                'pelayanan_online' => 2,
                'pelayanan_offline' => 2,
                'pendaftar' => 48,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 3,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 44,
                'nim' => 47,
                'bayar_ukt_reguler' => 44,
                'bayar_ukt_rpl' => 2,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2024-2025',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:53',
                'updated_at' => '2025-06-14 22:54:53',
            ),
            26 => 
            array (
                'id' => 27,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Komunikasi Dan Penyiaran Islam',
                'pelayanan_online' => 13,
                'pelayanan_offline' => 4,
                'pendaftar' => 45,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 6,
                'nim' => 9,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            27 => 
            array (
                'id' => 28,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
            'prodi' => 'Pendidikan Agama Islam (S1)',
                'pelayanan_online' => 42,
                'pelayanan_offline' => 15,
                'pendaftar' => 143,
                'bayar_form_reguler' => 11,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 3,
                'bayar_form_kipk' => 30,
                'nim' => 45,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            28 => 
            array (
                'id' => 29,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Pendidikan Guru Madrasah Ibtidaiyah',
                'pelayanan_online' => 16,
                'pelayanan_offline' => 2,
                'pendaftar' => 100,
                'bayar_form_reguler' => 16,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 22,
                'nim' => 40,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            29 => 
            array (
                'id' => 30,
                'fakultas' => 'FAKULTAS AGAMA ISLAM',
                'prodi' => 'Perbankan Syari`ah',
                'pelayanan_online' => 4,
                'pelayanan_offline' => 4,
                'pendaftar' => 57,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 7,
                'nim' => 11,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            30 => 
            array (
                'id' => 31,
                'fakultas' => 'FAKULTAS EKONOMI',
                'prodi' => 'Akuntansi',
                'pelayanan_online' => 18,
                'pelayanan_offline' => 5,
                'pendaftar' => 116,
                'bayar_form_reguler' => 5,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 2,
                'bayar_form_kipk' => 36,
                'nim' => 44,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            31 => 
            array (
                'id' => 32,
                'fakultas' => 'FAKULTAS EKONOMI',
                'prodi' => 'Manajemen',
                'pelayanan_online' => 60,
                'pelayanan_offline' => 29,
                'pendaftar' => 231,
                'bayar_form_reguler' => 10,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 2,
                'bayar_form_kipk' => 65,
                'nim' => 77,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            32 => 
            array (
                'id' => 33,
                'fakultas' => 'FAKULTAS HUKUM',
            'prodi' => 'Ilmu Hukum (S1)',
                'pelayanan_online' => 48,
                'pelayanan_offline' => 20,
                'pendaftar' => 140,
                'bayar_form_reguler' => 14,
                'bayar_form_rpl' => 4,
                'bayar_form_karyawan' => 6,
                'bayar_form_kipk' => 27,
                'nim' => 51,
                'bayar_ukt_reguler' => 4,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            33 => 
            array (
                'id' => 34,
                'fakultas' => 'FAKULTAS ILMU KOMUNIKASI',
                'prodi' => 'Ilmu Komunikasi',
                'pelayanan_online' => 29,
                'pelayanan_offline' => 11,
                'pendaftar' => 181,
                'bayar_form_reguler' => 8,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 56,
                'nim' => 64,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            34 => 
            array (
                'id' => 35,
                'fakultas' => 'FAKULTAS ILMU KOMUNIKASI',
                'prodi' => 'Ilmu Perpustakaan',
                'pelayanan_online' => 9,
                'pelayanan_offline' => 1,
                'pendaftar' => 16,
                'bayar_form_reguler' => 2,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 1,
                'nim' => 3,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            35 => 
            array (
                'id' => 36,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Arab',
                'pelayanan_online' => 18,
                'pelayanan_offline' => 5,
                'pendaftar' => 44,
                'bayar_form_reguler' => 9,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 6,
                'nim' => 15,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            36 => 
            array (
                'id' => 37,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Dan Sastra Indonesia',
                'pelayanan_online' => 12,
                'pelayanan_offline' => 18,
                'pendaftar' => 91,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 28,
                'nim' => 31,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            37 => 
            array (
                'id' => 38,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Bahasa Inggris',
                'pelayanan_online' => 13,
                'pelayanan_offline' => 6,
                'pendaftar' => 60,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 11,
                'nim' => 15,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            38 => 
            array (
                'id' => 39,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Guru Pendidikan Anak Usia Dini',
                'pelayanan_online' => 11,
                'pelayanan_offline' => 5,
                'pendaftar' => 40,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 7,
                'nim' => 8,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            39 => 
            array (
                'id' => 40,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Luar Biasa',
                'pelayanan_online' => 43,
                'pelayanan_offline' => 15,
                'pendaftar' => 80,
                'bayar_form_reguler' => 28,
                'bayar_form_rpl' => 4,
                'bayar_form_karyawan' => 7,
                'bayar_form_kipk' => 8,
                'nim' => 47,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            40 => 
            array (
                'id' => 41,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Masyarakat',
                'pelayanan_online' => 3,
                'pelayanan_offline' => 0,
                'pendaftar' => 34,
                'bayar_form_reguler' => 0,
                'bayar_form_rpl' => 2,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 14,
                'nim' => 16,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            41 => 
            array (
                'id' => 42,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Matematika',
                'pelayanan_online' => 8,
                'pelayanan_offline' => 7,
                'pendaftar' => 48,
                'bayar_form_reguler' => 2,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 26,
                'nim' => 29,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            42 => 
            array (
                'id' => 43,
                'fakultas' => 'FAKULTAS KEGURUAN DAN ILMU PENDIDIKAN',
                'prodi' => 'Pendidikan Pancasila dan Kewarganegaraan',
                'pelayanan_online' => 3,
                'pelayanan_offline' => 6,
                'pendaftar' => 42,
                'bayar_form_reguler' => 1,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 10,
                'nim' => 12,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            43 => 
            array (
                'id' => 44,
                'fakultas' => 'FAKULTAS PERTANIAN',
                'prodi' => 'Agroteknologi',
                'pelayanan_online' => 17,
                'pelayanan_offline' => 4,
                'pendaftar' => 79,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 31,
                'nim' => 37,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            44 => 
            array (
                'id' => 45,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Administrasi Pendidikan',
                'pelayanan_online' => 38,
                'pelayanan_offline' => 10,
                'pendaftar' => 67,
                'bayar_form_reguler' => 7,
                'bayar_form_rpl' => 12,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 19,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 1,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            45 => 
            array (
                'id' => 46,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Ilmu Hukum',
                'pelayanan_online' => 19,
                'pelayanan_offline' => 14,
                'pendaftar' => 24,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 6,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 10,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            46 => 
            array (
                'id' => 47,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S2 - Pendidikan Agama Islam',
                'pelayanan_online' => 15,
                'pelayanan_offline' => 5,
                'pendaftar' => 18,
                'bayar_form_reguler' => 5,
                'bayar_form_rpl' => 3,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 8,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            47 => 
            array (
                'id' => 48,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S3 - Ilmu Pendidikan',
                'pelayanan_online' => 18,
                'pelayanan_offline' => 11,
                'pendaftar' => 14,
                'bayar_form_reguler' => 7,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 7,
                'bayar_ukt_reguler' => 2,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            48 => 
            array (
                'id' => 49,
                'fakultas' => 'PASCASARJANA',
                'prodi' => 'S3 - Pendidikan Agama Islam',
                'pelayanan_online' => 3,
                'pelayanan_offline' => 4,
                'pendaftar' => 14,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 0,
                'bayar_form_kipk' => 0,
                'nim' => 3,
                'bayar_ukt_reguler' => 1,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            49 => 
            array (
                'id' => 50,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Elektro',
                'pelayanan_online' => 16,
                'pelayanan_offline' => 8,
                'pendaftar' => 40,
                'bayar_form_reguler' => 4,
                'bayar_form_rpl' => 1,
                'bayar_form_karyawan' => 2,
                'bayar_form_kipk' => 11,
                'nim' => 18,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            50 => 
            array (
                'id' => 51,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Industri',
                'pelayanan_online' => 13,
                'pelayanan_offline' => 6,
                'pendaftar' => 83,
                'bayar_form_reguler' => 3,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 21,
                'nim' => 25,
                'bayar_ukt_reguler' => 2,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
            51 => 
            array (
                'id' => 52,
                'fakultas' => 'FAKULTAS TEKNIK',
                'prodi' => 'Teknik Informatika',
                'pelayanan_online' => 25,
                'pelayanan_offline' => 12,
                'pendaftar' => 103,
                'bayar_form_reguler' => 5,
                'bayar_form_rpl' => 0,
                'bayar_form_karyawan' => 1,
                'bayar_form_kipk' => 49,
                'nim' => 55,
                'bayar_ukt_reguler' => 0,
                'bayar_ukt_rpl' => 0,
                'bayar_ukt_karyawan' => 0,
                'angkatan' => '2025-2026',
                'created_by' => 'unknown',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-14 22:54:55',
                'updated_at' => '2025-06-14 22:54:55',
            ),
        ));
        
        
    }
}